version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
    - api_network
  api_instance_1:
    build: ./SuperSimpleAPI
    restart: always
    networks:
      - api_network
    environment:
      - MONGO_DB=api_db
    depends_on:
      - api_db
  api_instance_2:
    build: ./SuperSimpleAPI
    restart: always
    networks:
      - api_network
    environment:
      - MONGO_DB=api_db
    depends_on:
      - api_db  
  api_instance_3:
    build: ./SuperSimpleAPI 
    restart: always
    environment:
      - MONGO_DB=api_db
    networks:
      - api_network
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    networks:
      - api_network
    volumes:
      - api_db_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - api_network
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      - api_network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped

networks:
  api_network:
    driver: bridge

volumes:
  api_db_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
    