version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      -"80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
    - api_network
  api_instance_1:
    build:
      context: ./SuperSimpleAPI 
    image: super_simple_api:latest
    restart: always
    networks:
      - api_network
    environment:
      - MONGO_DB=api_db
    depends_on:
      - api_db
  api_instance_2:
    build:
      context: ./SuperSimpleAPI 
    image: super_simple_api:latest 
    restart: always
    networks:
      - api_network
    environment:
      - MONGO_DB=api_db
    depends_on:
      - api_db  
  api_instance_3:
    build:
      context: ./SuperSimpleAPI
    image: super_simple_api:latest  
    restart: always
    environment:
      - MONGO_DB=api_db
    networks:
      - api_network
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    networks:
      - api_network
    volumes:
      -api_db_data:/data/db

networks:
  api_network:
    driver: bridge
volumes:
  api_db_data:
    