version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
    - api_network
    - dev_network
  api_instance_1:
    build: ./SuperSimpleAPI
    restart: always
    networks:
      - api_network
    environment:
      - MONGO_DB=api_db
    depends_on:
      - api_db
      
  api_instance_2:
    build: ./SuperSimpleAPI
    restart: always
    networks:
      - api_network
    environment:
      - MONGO_DB=api_db
    depends_on:
      - api_db  
  api_instance_3:
    build: ./SuperSimpleAPI 
    restart: always
    environment:
      - MONGO_DB=api_db
    networks:
      - api_network
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    container_name: api_db
    networks:
      - api_network
    volumes:
      - api_db_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - dev_network
    command: 
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=http://localhost:9090/prometheus/
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
    restart: unless-stopped
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    networks:
      - dev_network
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost/grafana
    restart: unless-stopped

networks:
  api_network:
    driver: bridge
  dev_network:
    driver: bridge

volumes:
  api_db_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
    